{
    "0Lepton_18_VVV":{
         "WWW_4F_TuneCP5_13TeV-amcatnlo-pythia8":"",
    },
    "0Lepton_18_WJets":{
         "WJetsToQQ_HT-800toInf_qc19_3j_TuneCP5_13TeV-madgraphMLM-pythia8":"miss",
    },
    "0Lepton_18_ZJets":{
         "ZJetsToQQ_HT-800toInf_qc19_4j_TuneCP5_13TeV-madgraphMLM-pythia8":"miss",
    },
    "0Lepton_18_TT":{
         "TTToHadronic_TuneCP5_13TeV-powheg-pythia8":"miss",
         "TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8":"miss",
    },
    "0Lepton_18_ST":{
         "ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8":"",
         "ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8":"",
         "ST_t-channel_top_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8":"",
         "ST_t-channel_antitop_4f_inclusiveDecays_TuneCP5_13TeV-powhegV2-madspin-pythia8":"",
         "ST_s-channel_4f_hadronicDecays_TuneCP5_13TeV-amcatnlo-pythia8":"",
    },
    # QCD pt binned samples ?
    "0Lepton_18_QCD_HT":{
         "QCD_HT700to1000_TuneCP5_13TeV-madgraphMLM-pythia8":"miss",
         "QCD_HT1000to1500_TuneCP5_13TeV-madgraphMLM-pythia8":"miss",
         "QCD_HT1500to2000_TuneCP5_13TeV-madgraphMLM-pythia8":"miss",
         "QCD_HT2000toInf_TuneCP5_13TeV-madgraphMLM-pythia8":"miss",
    },
    "0Lepton_18_VV":{
         "WW_TuneCP5_13TeV-pythia8":"",
         "ZZ_TuneCP5_13TeV-pythia8":"",
         "WZ_TuneCP5_13TeV-pythia8":"",
    },
    "0Lepton_18_VH":{
         "WplusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8":"miss",
         "WminusH_HToBB_WToQQ_M125_13TeV_powheg_pythia8":"miss",
         "ZH_HToBB_ZToQQ_M125_13TeV_powheg_pythia8":"miss",
    },
}
